version: '3.1'

services:
  mongo:
    image: mongo
    container_name: mongo
    restart: always
    env_file:
      - ./environment/.env
    networks:
      - me-network
    ports:
      - "27017:27017"

  mongo-express:
    image: mongo-express
    container_name: mongo-express
    restart: always
    ports:
      - "127.0.0.1:8081:8081"  # Binding to localhost
    env_file:
      - ./environment/.env
    networks:
      - me-network

networks:
  me-network:
    driver: bridge

